### PR TITLE
Add CrashMod, RedBar, Play3rdPer, streamer-tools

### PR DESCRIPTION
**Pull request by ComputerElite**
I got a few suggestions for your json format as well:
- Could you make author an array so you can add mutliple authors?
- And could you add a long and short description so you could have a short one with a summary and then a longer one with instructions for the mod?

### CODE REVIEW

**Comment by BobbyShmurner** [comment]
The short and long descriptions could very easily be added, id just have to ask pink to see what she thinks.
As for the multiple authors, that was the plan originally, but it's pretty much impossible to deduce a list of pfps from just a qmod and a mod.json. I then thought of either adding support for an `authors.json` (which would just contain the info on the authors), or just having one author pfp. In the end, I just settled on having one author and one author pfp, cus that's what everything else uses and what everyone else is used to.
I'm not against the idea or anything, in fact, I'm honestly for the idea of multiple authors, but it just made the most sense to only have one author

(btw I'm very busy with school rn, so I have zero time to test out ur mods. Sorry bout that!)

**Comment by MillzyDev** [comment]
couldn't you just have an array of objects for the authors?
```json
...
"authors": [
    {
        "name": "Author1",
        "avatar": "https://somesite/someavatar.bmp"
    },
    {
        "name": "Author2",
        "avatar": "https://somesite/someotheravatar.bmp"
    },
]
```

**Comment by MillzyDev** [comment]
unless i'm stupid and missed something

**Comment by BobbyShmurner** [comment]
That's exactly what the original idea was. But as this is really
designed to work with the github action, there isn't really any way (that I
can think of) to determine the names and authors avatars without using an
`authors.json`

**Pull request closed without merging**
